export const GET_TOTAL_US_DATA = 'GET_TOTAL_US_DATA';
export const GET_TOTAL_US_DATA_FAILURE = 'GET_TOTAL_US_DATA_FAILURE';
export const GET_TOTAL_US_DATA_SUCCESS = 'GET_TOTAL_US_DATA_SUCCESS';

export const GET_ALL_STATES_DATA = 'GET_ALL_STATES_DATA';
export const GET_ALL_STATES_DATA_FAILURE = 'GET_ALL_STATES_DATA_FAILURE';
export const GET_ALL_STATES_DATA_SUCCESS = 'GET_ALL_STATES_DATA_SUCCESS';

export const GET_ALL_STATES_META = 'GET_ALL_STATES_META';
export const GET_ALL_STATES_META_FAILURE = 'GET_ALL_STATES_META_FAILURE';
export const GET_ALL_STATES_META_SUCCESS = 'GET_ALL_STATES_META_SUCCESS';
