export const GET_ALL_STATES_META = 'GET_ALL_STATES_META';
export const GET_ALL_STATES_META_FAILURE = 'GET_ALL_STATES_META_FAILURE';
export const GET_ALL_STATES_META_SUCCESS = 'GET_ALL_STATES_META_SUCCESS';

export const SELECT_STATE = 'SELECT_STATE';

export const GET_DAILY_DATA = 'GET_DAILY_DATA';
export const GET_DAILY_DATA_SUCCESS = 'GET_DAILY_DATA_SUCCESS';
export const GET_DAILY_DATA_FAILURE = 'GET_DAILY_DATA_FAILURE';
